preset: laravel

risky: false

enabled:
  - phpdoc_order
  - phpdoc_separation
  - standardize_increment
  - ternary_to_null_coalescing
  - concat_with_spaces

disabled:
  - not_operator_with_successor_space
  - concat_without_spaces

finder:
  exclude:
    - "public"
    - "node_modules"
    - "storage"
  name:
    - "*.php"
